name: amap_location_fluttify
description: An `Amap` Location Component, Powered By `Fluttify`, A Compiler Generating Dart Bindings For Native SDK.
version: 0.22.0
author: yohom <yohombao@qq.com>
homepage: https://github.com/fluttify-project/amap_location_fluttify
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.12.13"

dependencies:
  flutter:
    sdk: flutter
  
  
  foundation_fluttify: ^0.13.0+1
  core_location_fluttify: ^0.7.1
  amap_core_fluttify:
    git:
      url: https://github.com/super-lz/amap_core_fluttify.git
      ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

flutter:
  plugin:
    platforms:
      android:
        package: me.yohom.amap_location_fluttify
        pluginClass: AmapLocationFluttifyPlugin
      ios:
        pluginClass: AmapLocationFluttifyPlugin